// Generated by ReScript, PLEASE EDIT WITH CARE


let Storage = {};

let BrowserSettings = {};

let Privacy = {};

let Permissions = {};

let Runtime = {};

let Tabs = {};

let Notifications = {};

function isFirefox() {
  try {
    return true;
  } catch (exn) {
    return false;
  }
}

async function getBrowserCompat() {
  try {
    let info = await browser["runtime.getBrowserInfo"]();
    return {
      isGecko: true,
      geckoVersion: info.version,
      isFirefox: info.name.includes("Firefox"),
      isLibrewolf: info.name.includes("LibreWolf"),
      isWaterfox: info.name.includes("Waterfox"),
      isPaleMoon: info.name.includes("Pale Moon"),
      supportedFlags: []
    };
  } catch (exn) {
    return {
      isGecko: false,
      geckoVersion: undefined,
      isFirefox: false,
      isLibrewolf: false,
      isWaterfox: false,
      isPaleMoon: false,
      supportedFlags: []
    };
  }
}

export {
  Storage,
  BrowserSettings,
  Privacy,
  Permissions,
  Runtime,
  Tabs,
  Notifications,
  isFirefox,
  getBrowserCompat,
}
/* No side effect */
