// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function evaluateCode(code) {
  let call = (function(c) { return browser.devtools.inspectedWindow['eval'](c); });
  return call(code);
}

let DevToolsAPI = {
  evaluateCode: evaluateCode
};

async function collectPerformanceMetrics() {
  try {
    let match = await evaluateCode(`
      (function() {
        const perf = window.performance;
        const timing = perf.timing;
        const paint = perf.getEntriesByType('paint');
        const memory = performance.memory;

        return {
          navigationStart: timing.navigationStart,
          domContentLoaded: timing.domContentLoadedEventEnd - timing.navigationStart,
          loadComplete: timing.loadEventEnd - timing.navigationStart,
          firstPaint: paint.find(e => e.name === 'first-paint')?.startTime || null,
          firstContentfulPaint: paint.find(e => e.name === 'first-contentful-paint')?.startTime || null,
          memoryUsage: memory ? memory.usedJSHeapSize : null,
          jsHeapSize: memory ? memory.totalJSHeapSize : null
        };
      })()
    `);
    if (match[1] !== undefined) {
      return {
        TAG: "Error",
        _0: "Failed to collect performance metrics"
      };
    }
    let dict = Js_json.decodeObject(match[0]);
    if (dict === undefined) {
      return {
        TAG: "Error",
        _0: "Failed to decode metrics object"
      };
    }
    let getNum = key => {
      let v = Js_dict.get(dict, key);
      if (v !== undefined) {
        return Js_json.decodeNumber(v);
      }
    };
    let match$1 = getNum("navigationStart");
    let match$2 = getNum("domContentLoaded");
    let match$3 = getNum("loadComplete");
    if (match$1 === undefined) {
      return {
        TAG: "Error",
        _0: "Missing required metrics fields"
      };
    }
    if (match$2 === undefined) {
      return {
        TAG: "Error",
        _0: "Missing required metrics fields"
      };
    }
    if (match$3 === undefined) {
      return {
        TAG: "Error",
        _0: "Missing required metrics fields"
      };
    }
    let metrics_firstPaint = getNum("firstPaint");
    let metrics_firstContentfulPaint = getNum("firstContentfulPaint");
    let metrics_memoryUsage = getNum("memoryUsage");
    let metrics_jsHeapSize = getNum("jsHeapSize");
    let metrics = {
      navigationStart: match$1,
      domContentLoaded: match$2,
      loadComplete: match$3,
      firstPaint: metrics_firstPaint,
      firstContentfulPaint: metrics_firstContentfulPaint,
      memoryUsage: metrics_memoryUsage,
      jsHeapSize: metrics_jsHeapSize
    };
    return {
      TAG: "Ok",
      _0: metrics
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Stdlib_Option.getOr(Stdlib_JsExn.message(exn._1), "Unknown error")
      };
    } else {
      return {
        TAG: "Error",
        _0: "Unknown error"
      };
    }
  }
}

function calculateFlagImpact(flag, before, after) {
  let beforeTime = before.loadComplete;
  let afterTime = after.loadComplete;
  let change = (afterTime - beforeTime) / beforeTime * 100.0;
  return {
    flag: flag,
    metricsBefore: before,
    metricsAfter: after,
    percentChange: change,
    improved: change < 0.0
  };
}

async function createDevToolsPanel() {
  try {
    let panel = await browser.devtools.panels.create("FireFlag", "../icons/fireflag-32.png", "../devtools/panel.html");
    return {
      TAG: "Ok",
      _0: panel
    };
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Stdlib_Option.getOr(Stdlib_JsExn.message(exn._1), "Failed to create DevTools panel")
      };
    } else {
      return {
        TAG: "Error",
        _0: "Failed to create DevTools panel"
      };
    }
  }
}

function exportMetricsReport(state) {
  let m = state.metrics;
  let tmp;
  if (m !== undefined) {
    let dict = {};
    dict["navigationStart"] = m.navigationStart;
    dict["domContentLoaded"] = m.domContentLoaded;
    dict["loadComplete"] = m.loadComplete;
    tmp = dict;
  } else {
    tmp = undefined;
  }
  return {
    timestamp: Date.now(),
    browserVersion: "unknown",
    geckoVersion: "unknown",
    flagChanges: [],
    performanceMetrics: tmp,
    notes: "DevTools performance analysis"
  };
}

export {
  DevToolsAPI,
  collectPerformanceMetrics,
  calculateFlagImpact,
  createDevToolsPanel,
  exportMetricsReport,
}
/* Stdlib_JsExn Not a pure module */
