// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "std/assert";

let undefinedV = undefined;

function create() {
  return {
    state: {
      initialized: false,
      databaseLoaded: false,
      database: {},
      flagChanges: []
    },
    devToolsPanel: {
      visible: false,
      flags: [],
      selectedFlag: undefined
    }
  };
}

function cloneDb(db) {
  let out = {};
  Object.keys(db).forEach(k => {
    let f = db[k];
    if (f !== undefined) {
      out[k] = f;
      return;
    }
  });
  return out;
}

async function initialize(ext) {
  ext.state.initialized = true;
}

async function loadDatabase(ext, db) {
  ext.state.database = cloneDb(db);
  ext.state.databaseLoaded = true;
}

function evaluateFlag(ext, flagId) {
  let flag = ext.state.database[flagId];
  if (flag !== undefined) {
    if (flag.enabled) {
      return flag.value;
    } else {
      return flag.defaultValue;
    }
  } else {
    return undefinedV;
  }
}

async function updateDatabase(ext, newDb) {
  let oldDb = ext.state.database;
  Object.keys(newDb).forEach(key => {
    let newFlag = newDb[key];
    let old = oldDb[key];
    let changed = old !== undefined ? JSON.stringify(old) !== JSON.stringify(newFlag) : true;
    if (changed) {
      ext.state.flagChanges.push({
        key: key,
        timestamp: Date.now()
      });
      return;
    }
  });
  ext.state.database = cloneDb(newDb);
}

function getAllFlags(ext) {
  return Object.values(ext.state.database);
}

function getFlagsByCategory(ext, category) {
  let prefix = category + ".";
  return Object.values(ext.state.database).filter(f => f.key.startsWith(prefix));
}

async function openDevToolsPanel(ext) {
  ext.devToolsPanel.visible = true;
  ext.devToolsPanel.flags = Object.values(ext.state.database);
}

function inspectFlag(ext, flagId) {
  ext.devToolsPanel.selectedFlag = flagId;
}

function countFlags(ext, predicate) {
  return Object.values(ext.state.database).filter(predicate).length;
}

function notifyFlagChanged(ext, flagId, newValue) {
  let flag = ext.state.database[flagId];
  if (flag !== undefined) {
    flag.value = newValue;
    ext.state.flagChanges.push({
      key: flagId,
      timestamp: Date.now()
    });
    return;
  }
}

function getChangeHistory(ext) {
  return ext.state.flagChanges;
}

function reset(ext) {
  ext.state = {
    initialized: false,
    databaseLoaded: false,
    database: {},
    flagChanges: []
  };
  ext.devToolsPanel = {
    visible: false,
    flags: [],
    selectedFlag: undefined
  };
}

function mkFlag(key, enabled, value, defaultValue) {
  return {
    key: key,
    enabled: enabled,
    value: value,
    defaultValue: defaultValue
  };
}

function singleton(key, flag) {
  let d = {};
  d[key] = flag;
  return d;
}

Deno.test("E2E: initialize extension", async () => {
  let ext = create();
  Assert.assertEquals(ext.state.initialized, false);
  await initialize(ext);
  Assert.assertEquals(ext.state.initialized, true);
  return reset(ext);
});

Deno.test("E2E: load flag database after initialization", async () => {
  let ext = create();
  let db = singleton("privacy.tracking", {
    key: "privacy.tracking",
    enabled: true,
    value: false,
    defaultValue: true
  });
  await initialize(ext);
  Assert.assertEquals(ext.state.databaseLoaded, false);
  await loadDatabase(ext, db);
  Assert.assertEquals(ext.state.databaseLoaded, true);
  Assert.assertEquals(Object.keys(ext.state.database).length, 1);
  return reset(ext);
});

Deno.test("E2E: initialize → load database → evaluate flag", async () => {
  let ext = create();
  let db = singleton("feature.new", {
    key: "feature.new",
    enabled: true,
    value: true,
    defaultValue: false
  });
  await initialize(ext);
  Assert.assertExists(ext.state.initialized);
  await loadDatabase(ext, db);
  Assert.assertExists(ext.state.database["feature.new"]);
  let result = evaluateFlag(ext, "feature.new");
  Assert.assertStrictEquals(result, true);
  return reset(ext);
});

Deno.test("E2E: evaluate multiple flags", async () => {
  let ext = create();
  let db = {};
  db["feature.one"] = {
    key: "feature.one",
    enabled: true,
    value: "first",
    defaultValue: "default"
  };
  db["feature.two"] = {
    key: "feature.two",
    enabled: false,
    value: "second",
    defaultValue: "default"
  };
  db["feature.three"] = {
    key: "feature.three",
    enabled: true,
    value: 42,
    defaultValue: 0
  };
  await initialize(ext);
  await loadDatabase(ext, db);
  Assert.assertEquals(evaluateFlag(ext, "feature.one"), "first");
  Assert.assertEquals(evaluateFlag(ext, "feature.two"), "default");
  Assert.assertEquals(evaluateFlag(ext, "feature.three"), 42);
  Assert.assertEquals(evaluateFlag(ext, "nonexistent"), undefinedV);
  return reset(ext);
});

Deno.test("E2E: update database → re-evaluate → see new values", async () => {
  let ext = create();
  let db1 = singleton("feature.beta", {
    key: "feature.beta",
    enabled: true,
    value: false,
    defaultValue: false
  });
  await initialize(ext);
  await loadDatabase(ext, db1);
  Assert.assertStrictEquals(evaluateFlag(ext, "feature.beta"), false);
  let db2 = singleton("feature.beta", {
    key: "feature.beta",
    enabled: true,
    value: true,
    defaultValue: false
  });
  await updateDatabase(ext, db2);
  Assert.assertStrictEquals(evaluateFlag(ext, "feature.beta"), true);
  return reset(ext);
});

Deno.test("E2E: database update tracks changes", async () => {
  let ext = create();
  let db1 = {};
  db1["feature.a"] = {
    key: "feature.a",
    enabled: true,
    value: 1,
    defaultValue: 0
  };
  db1["feature.b"] = {
    key: "feature.b",
    enabled: true,
    value: 2,
    defaultValue: 0
  };
  await initialize(ext);
  await loadDatabase(ext, db1);
  let db2 = {};
  db2["feature.a"] = {
    key: "feature.a",
    enabled: true,
    value: 100,
    defaultValue: 0
  };
  db2["feature.b"] = {
    key: "feature.b",
    enabled: true,
    value: 2,
    defaultValue: 0
  };
  db2["feature.c"] = {
    key: "feature.c",
    enabled: true,
    value: 3,
    defaultValue: 0
  };
  await updateDatabase(ext, db2);
  let history = ext.state.flagChanges;
  Assert.assertEquals(history.length >= 2, true);
  Assert.assertEquals(history.some(h => h.key === "feature.a"), true);
  Assert.assertEquals(history.some(h => h.key === "feature.c"), true);
  return reset(ext);
});

Deno.test("E2E: open DevTools panel", async () => {
  let ext = create();
  let db = singleton("feature.test", {
    key: "feature.test",
    enabled: true,
    value: true,
    defaultValue: false
  });
  await initialize(ext);
  await loadDatabase(ext, db);
  Assert.assertEquals(ext.devToolsPanel.visible, false);
  await openDevToolsPanel(ext);
  Assert.assertEquals(ext.devToolsPanel.visible, true);
  Assert.assertEquals(ext.devToolsPanel.flags.length, 1);
  return reset(ext);
});

Deno.test("E2E: DevTools inspect flag", async () => {
  let ext = create();
  let db = {};
  db["privacy.tracking"] = {
    key: "privacy.tracking",
    enabled: true,
    value: false,
    defaultValue: true
  };
  db["perf.cache"] = {
    key: "perf.cache",
    enabled: false,
    value: true,
    defaultValue: false
  };
  await initialize(ext);
  await loadDatabase(ext, db);
  await openDevToolsPanel(ext);
  inspectFlag(ext, "privacy.tracking");
  Assert.assertEquals(ext.devToolsPanel.selectedFlag, "privacy.tracking");
  return reset(ext);
});

Deno.test("E2E: DevTools list all flags", async () => {
  let ext = create();
  let db = {};
  db["privacy.tracking"] = {
    key: "privacy.tracking",
    enabled: true,
    value: false,
    defaultValue: true
  };
  db["privacy.cookies"] = {
    key: "privacy.cookies",
    enabled: true,
    value: false,
    defaultValue: true
  };
  db["perf.cache"] = {
    key: "perf.cache",
    enabled: false,
    value: true,
    defaultValue: false
  };
  await initialize(ext);
  await loadDatabase(ext, db);
  await openDevToolsPanel(ext);
  Assert.assertEquals(ext.devToolsPanel.flags.length, 3);
  return reset(ext);
});

Deno.test("E2E: DevTools count matches", async () => {
  let ext = create();
  let db = {};
  db["privacy.tracking"] = {
    key: "privacy.tracking",
    enabled: true,
    value: false,
    defaultValue: true
  };
  db["privacy.cookies"] = {
    key: "privacy.cookies",
    enabled: true,
    value: false,
    defaultValue: true
  };
  db["perf.cache"] = {
    key: "perf.cache",
    enabled: false,
    value: true,
    defaultValue: false
  };
  db["perf.network"] = {
    key: "perf.network",
    enabled: true,
    value: true,
    defaultValue: false
  };
  await initialize(ext);
  await loadDatabase(ext, db);
  let enabledCount = countFlags(ext, f => f.enabled);
  Assert.assertEquals(enabledCount, 3);
  let privacyFlags = getFlagsByCategory(ext, "privacy");
  Assert.assertEquals(privacyFlags.length, 2);
  let perfFlags = getFlagsByCategory(ext, "perf");
  Assert.assertEquals(perfFlags.length, 2);
  return reset(ext);
});

Deno.test("E2E: flag changed → extension notified → state updated", async () => {
  let ext = create();
  let db = singleton("feature.experimental", {
    key: "feature.experimental",
    enabled: true,
    value: false,
    defaultValue: false
  });
  await initialize(ext);
  await loadDatabase(ext, db);
  Assert.assertEquals(evaluateFlag(ext, "feature.experimental"), false);
  notifyFlagChanged(ext, "feature.experimental", true);
  Assert.assertEquals(evaluateFlag(ext, "feature.experimental"), true);
  let history = ext.state.flagChanges;
  Assert.assertEquals(history.some(h => h.key === "feature.experimental"), true);
  return reset(ext);
});

Deno.test("E2E: multiple flag changes tracked", async () => {
  let ext = create();
  let db = {};
  db["flag.a"] = {
    key: "flag.a",
    enabled: true,
    value: 1,
    defaultValue: 0
  };
  db["flag.b"] = {
    key: "flag.b",
    enabled: true,
    value: 2,
    defaultValue: 0
  };
  db["flag.c"] = {
    key: "flag.c",
    enabled: true,
    value: 3,
    defaultValue: 0
  };
  await initialize(ext);
  await loadDatabase(ext, db);
  notifyFlagChanged(ext, "flag.a", 10);
  notifyFlagChanged(ext, "flag.b", 20);
  notifyFlagChanged(ext, "flag.c", 30);
  Assert.assertEquals(evaluateFlag(ext, "flag.a"), 10);
  Assert.assertEquals(evaluateFlag(ext, "flag.b"), 20);
  Assert.assertEquals(evaluateFlag(ext, "flag.c"), 30);
  let history = ext.state.flagChanges;
  Assert.assertEquals(history.length, 3);
  return reset(ext);
});

Deno.test("E2E: complete workflow: init → load → devtools → update → verify", async () => {
  let ext = create();
  await initialize(ext);
  Assert.assertExists(ext.state.initialized);
  let db1 = {};
  db1["feature.alpha"] = {
    key: "feature.alpha",
    enabled: true,
    value: "v1",
    defaultValue: "default"
  };
  db1["feature.beta"] = {
    key: "feature.beta",
    enabled: false,
    value: "v2",
    defaultValue: "disabled"
  };
  await loadDatabase(ext, db1);
  Assert.assertEquals(Object.keys(ext.state.database).length, 2);
  Assert.assertEquals(evaluateFlag(ext, "feature.alpha"), "v1");
  Assert.assertEquals(evaluateFlag(ext, "feature.beta"), "disabled");
  await openDevToolsPanel(ext);
  Assert.assertEquals(ext.devToolsPanel.visible, true);
  Assert.assertEquals(ext.devToolsPanel.flags.length, 2);
  inspectFlag(ext, "feature.alpha");
  Assert.assertEquals(ext.devToolsPanel.selectedFlag, "feature.alpha");
  let db2 = {};
  db2["feature.alpha"] = {
    key: "feature.alpha",
    enabled: true,
    value: "v1-updated",
    defaultValue: "default"
  };
  db2["feature.beta"] = {
    key: "feature.beta",
    enabled: true,
    value: "v2-updated",
    defaultValue: "disabled"
  };
  db2["feature.gamma"] = {
    key: "feature.gamma",
    enabled: true,
    value: "v3",
    defaultValue: "default"
  };
  await updateDatabase(ext, db2);
  Assert.assertEquals(evaluateFlag(ext, "feature.alpha"), "v1-updated");
  Assert.assertEquals(evaluateFlag(ext, "feature.beta"), "v2-updated");
  Assert.assertEquals(evaluateFlag(ext, "feature.gamma"), "v3");
  let updatedFlags = Object.values(ext.state.database);
  Assert.assertEquals(updatedFlags.length, 3);
  return reset(ext);
});

export {
  undefinedV,
  create,
  cloneDb,
  initialize,
  loadDatabase,
  evaluateFlag,
  updateDatabase,
  getAllFlags,
  getFlagsByCategory,
  openDevToolsPanel,
  inspectFlag,
  countFlags,
  notifyFlagChanged,
  getChangeHistory,
  reset,
  mkFlag,
  singleton,
}
/*  Not a pure module */
