// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "std/assert";

let undefinedV = undefined;

let nullV = null;

function evaluateFlag(flagId, database) {
  let flag = database[flagId];
  if (flag !== undefined) {
    if (flag.enabled) {
      return flag.value;
    } else {
      return flag.defaultValue;
    }
  } else {
    return undefinedV;
  }
}

function serializeDatabase(db) {
  return JSON.stringify(db);
}

function deserializeDatabase(json) {
  return JSON.parse(json);
}

function deepEqual(a, b) {
  if ((function(x,y){return x===y})(a, b)) {
    return true;
  }
  if (typeof a !== typeof b) {
    return false;
  }
  if (typeof a !== "object" || (function(x){return x===null})(a) || (function(x){return x===null})(b)) {
    return false;
  }
  let aKeys = Object.keys(a);
  let bKeys = Object.keys(b);
  if (aKeys.length !== bKeys.length) {
    return false;
  } else {
    return aKeys.every(k => {
      let av = (function(o,k){return o[k]})(a, k);
      let bv = (function(o,k){return o[k]})(b, k);
      return deepEqual(av, bv);
    });
  }
}

function mkFlag(key, enabled, value, defaultValue) {
  return {
    key: key,
    enabled: enabled,
    value: value,
    defaultValue: defaultValue
  };
}

function singleton(key, flag) {
  let d = {};
  d[key] = flag;
  return d;
}

Deno.test("Property: flag evaluation is deterministic", () => {
  let db = singleton("feature.test", {
    key: "feature.test",
    enabled: true,
    value: 42,
    defaultValue: 0
  });
  let results = [];
  for (let _for = 0; _for <= 99; ++_for) {
    results.push(evaluateFlag("feature.test", db));
  }
  let firstResult = results[0];
  results.forEach(result => {
    Assert.assertStrictEquals(result, firstResult);
  });
});

Deno.test("Property: evaluation of disabled flag is deterministic", () => {
  let db = singleton("feature.disabled", {
    key: "feature.disabled",
    enabled: false,
    value: "should-not-return",
    defaultValue: "should-return"
  });
  for (let _for = 0; _for <= 99; ++_for) {
    let result = evaluateFlag("feature.disabled", db);
    Assert.assertStrictEquals(result, "should-return");
  }
});

Deno.test("Property: evaluation of missing flag is deterministic", () => {
  let db = {};
  for (let _for = 0; _for <= 99; ++_for) {
    let result = evaluateFlag("nonexistent.flag", db);
    Assert.assertStrictEquals(result, undefinedV);
  }
});

Deno.test("Property: disabled flag NEVER returns non-default value (invariant)", () => {
  let cases = [
    [
      true,
      false
    ],
    [
      42,
      0
    ],
    [
      "enabled",
      "disabled"
    ],
    [
      {
        nested: "object"
      },
      {
        nested: "default"
      }
    ],
    [
      [
        1,
        2,
        3
      ],
      []
    ]
  ];
  cases.forEach(param => {
    let d = param[1];
    let db = singleton("feature.disabled", mkFlag("feature.disabled", false, param[0], d));
    let result = evaluateFlag("feature.disabled", db);
    Assert.assertEquals(deepEqual(result, d), true);
  });
});

Deno.test("Property: enabled flag always returns value when available", () => {
  let cases = [
    true,
    false,
    0,
    42,
    -100,
    "string",
    "",
    {
      key: "value"
    },
    [
      1,
      2,
      3
    ]
  ];
  cases.forEach(value => {
    let db = singleton("feature.enabled", mkFlag("feature.enabled", true, value, "default"));
    let result = evaluateFlag("feature.enabled", db);
    Assert.assertEquals(deepEqual(result, value), true);
  });
});

Deno.test("Property: flag ID is always a string in database", () => {
  let db = {};
  db["feature.one"] = {
    key: "feature.one",
    enabled: true,
    value: 1,
    defaultValue: 0
  };
  db["feature.two"] = {
    key: "feature.two",
    enabled: false,
    value: 2,
    defaultValue: 0
  };
  db["feature.three"] = {
    key: "feature.three",
    enabled: true,
    value: 3,
    defaultValue: 0
  };
  Object.keys(db).forEach(id => {
    let flag = db[id];
    Assert.assertEquals(typeof id, "string");
    Assert.assertEquals(typeof flag.key, "string");
    Assert.assertExists(id);
    Assert.assertExists(flag.key);
  });
});

Deno.test("Property: flag key never contains null/undefined", () => {
  let db = {};
  db["privacy.tracking"] = {
    key: "privacy.tracking",
    enabled: true,
    value: false,
    defaultValue: true
  };
  db["perf.cache"] = {
    key: "perf.cache",
    enabled: false,
    value: true,
    defaultValue: false
  };
  Object.values(db).forEach(flag => {
    let notNull = (function(x){return x!==null && x!==undefined})(flag.key);
    Assert.assertEquals(notNull, true);
    Assert.assertEquals(flag.key.length > 0, true);
  });
});

Deno.test("Property: database serialization round-trips correctly", () => {
  let original = {};
  original["feature.one"] = {
    key: "feature.one",
    enabled: true,
    value: 42,
    defaultValue: 0
  };
  original["feature.two"] = {
    key: "feature.two",
    enabled: false,
    value: "never-returned",
    defaultValue: "default"
  };
  original["feature.three"] = {
    key: "feature.three",
    enabled: true,
    value: false,
    defaultValue: true
  };
  let json = JSON.stringify(original);
  Assert.assertEquals(typeof json, "string");
  let restored = JSON.parse(json);
  Object.keys(original).forEach(id => {
    let o = original[id];
    let r = restored[id];
    Assert.assertExists(r);
    Assert.assertEquals(r.key, o.key);
    Assert.assertEquals(r.enabled, o.enabled);
    Assert.assertEquals(deepEqual(r.value, o.value), true);
    Assert.assertEquals(deepEqual(r.defaultValue, o.defaultValue), true);
  });
});

Deno.test("Property: evaluation identical before/after serialization", () => {
  let original = singleton("feature.test", {
    key: "feature.test",
    enabled: true,
    value: "original-value",
    defaultValue: "default"
  });
  let beforeResult = evaluateFlag("feature.test", original);
  let json = JSON.stringify(original);
  let restored = JSON.parse(json);
  let afterResult = evaluateFlag("feature.test", restored);
  Assert.assertStrictEquals(afterResult, beforeResult);
});

Deno.test("Property: complex nested values round-trip correctly", () => {
  let complexValue = {
    nested: {
      deep: {
        array: [
          1,
          2,
          3
        ],
        string: "value",
        bool: true
      }
    }
  };
  let original = singleton("feature.complex", mkFlag("feature.complex", true, complexValue, {
    default: "value"
  }));
  let json = JSON.stringify(original);
  let restored = JSON.parse(json);
  let originalResult = evaluateFlag("feature.complex", original);
  let restoredResult = evaluateFlag("feature.complex", restored);
  Assert.assertEquals(deepEqual(originalResult, restoredResult), true);
});

Deno.test("Property: 1000 flags maintain determinism", () => {
  let db = {};
  for (let i = 0; i <= 999; ++i) {
    db["flag." + i.toString()] = mkFlag("flag." + i.toString(), i % 3 === 0, i, 0);
  }
  let firstPass = {};
  let secondPass = {};
  for (let i$1 = 0; i$1 <= 999; ++i$1) {
    firstPass[i$1.toString()] = evaluateFlag("flag." + i$1.toString(), db);
    secondPass[i$1.toString()] = evaluateFlag("flag." + i$1.toString(), db);
  }
  for (let i$2 = 0; i$2 <= 999; ++i$2) {
    Assert.assertStrictEquals(firstPass[i$2.toString()], secondPass[i$2.toString()]);
  }
});

Deno.test("Property: disabled flag invariant holds for 1000 flags", () => {
  let db = {};
  for (let i = 0; i <= 999; ++i) {
    db["flag." + i.toString()] = mkFlag("flag." + i.toString(), false, "value-" + i.toString(), "default-" + i.toString());
  }
  for (let i$1 = 0; i$1 <= 999; ++i$1) {
    let result = evaluateFlag("flag." + i$1.toString(), db);
    Assert.assertStrictEquals(result, "default-" + i$1.toString());
  }
});

Deno.test("Property: large database serialization round-trip", () => {
  let db = {};
  for (let i = 0; i <= 499; ++i) {
    db["flag." + i.toString()] = mkFlag("flag." + i.toString(), i % 2 === 0, {
      index: i,
      enabled: i % 2 === 0
    }, {
      index: i,
      enabled: false
    });
  }
  let json = JSON.stringify(db);
  let restored = JSON.parse(json);
  let matches = 0;
  for (let i$1 = 0; i$1 <= 499; ++i$1) {
    let orig = evaluateFlag("flag." + i$1.toString(), db);
    let rest = evaluateFlag("flag." + i$1.toString(), restored);
    if (deepEqual(orig, rest)) {
      matches = matches + 1 | 0;
    }
  }
  Assert.assertEquals(matches, 500);
});

Deno.test("Property: empty string flag ID returns undefined", () => {
  let db = {};
  let result = evaluateFlag("", db);
  Assert.assertStrictEquals(result, undefinedV);
});

Deno.test("Property: flag with null value (when enabled) returns null", () => {
  let db = singleton("feature.null-value", mkFlag("feature.null-value", true, nullV, "default"));
  let result = evaluateFlag("feature.null-value", db);
  Assert.assertStrictEquals(result, nullV);
});

Deno.test("Property: flag with undefined default is accessible", () => {
  let db = singleton("feature.undefined-default", mkFlag("feature.undefined-default", false, "value", undefinedV));
  let result = evaluateFlag("feature.undefined-default", db);
  Assert.assertStrictEquals(result, undefinedV);
});

Deno.test("Property: boolean false values are preserved (not converted to falsy)", () => {
  let db = singleton("feature.bool-false", {
    key: "feature.bool-false",
    enabled: true,
    value: false,
    defaultValue: true
  });
  let result = evaluateFlag("feature.bool-false", db);
  Assert.assertStrictEquals(result, false);
  Assert.assertEquals(typeof result, "boolean");
});

Deno.test("Property: zero values are preserved (not converted to falsy)", () => {
  let db = singleton("feature.zero", {
    key: "feature.zero",
    enabled: true,
    value: 0,
    defaultValue: 100
  });
  let result = evaluateFlag("feature.zero", db);
  Assert.assertStrictEquals(result, 0);
});

export {
  undefinedV,
  nullV,
  evaluateFlag,
  serializeDatabase,
  deserializeDatabase,
  deepEqual,
  mkFlag,
  singleton,
}
/*  Not a pure module */
