// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "std/assert";

let idRegex = /^[a-zA-Z0-9._-]+$/;

function isValidFlagId(id) {
  if (typeof id !== "string" || id.length === 0) {
    return false;
  } else {
    return idRegex.test(id);
  }
}

let d = {};

d["&"] = "&amp;";

d["<"] = "&lt;";

d[">"] = "&gt;";

d["\""] = "&quot;";

d["'"] = "&#039;";

let htmlEscapeRegex = /[&<>"']/g;

function escapeHtml(text) {
  if (typeof text !== "string") {
    return (function(x){return String(x)})(text);
  } else {
    return text.replace(htmlEscapeRegex, (function(ch){
      const map = {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"};
      return map[ch];
    }));
  }
}

function getSafeValue(flag) {
  if (!flag.enabled) {
    return escapeHtml(JSON.stringify(flag.defaultValue));
  }
  let value = flag.value;
  if (typeof value === "string") {
    return escapeHtml(value);
  } else {
    return escapeHtml(JSON.stringify(value));
  }
}

function validateJson(json) {
  try {
    JSON.parse(json);
    return true;
  } catch (exn) {
    return false;
  }
}

function safeParseJson(json, fallback) {
  try {
    return JSON.parse(json);
  } catch (exn) {
    return fallback;
  }
}

function isFlagReadonly(flag) {
  return flag.readonly_;
}

function modifyFlag(flagId, newValue, database) {
  if (!isValidFlagId(flagId)) {
    return {
      success: false,
      error: "Invalid flag ID"
    };
  }
  let flag = database[flagId];
  if (flag !== undefined) {
    if (flag.readonly_) {
      return {
        success: false,
        error: "Flag is readonly"
      };
    } else {
      flag.value = newValue;
      return {
        success: true,
        error: undefined
      };
    }
  } else {
    return {
      success: false,
      error: "Flag not found"
    };
  }
}

function mkFlag(key, enabled, value, defaultValue, readonlyOpt, param) {
  let readonly = readonlyOpt !== undefined ? readonlyOpt : false;
  return {
    key: key,
    enabled: enabled,
    value: value,
    defaultValue: defaultValue,
    readonly_: readonly
  };
}

function singleton(key, flag) {
  let d = {};
  d[key] = flag;
  return d;
}

Deno.test("Security: reject path traversal in flag IDs", () => {
  let maliciousIds = [
    "../../../etc/passwd",
    "..\\..\\..\\windows\\system32",
    "flag./../../../config",
    "feature/../../../../secrets"
  ];
  maliciousIds.forEach(id => {
    Assert.assertEquals(isValidFlagId(id), false);
  });
});

Deno.test("Security: reject null bytes in flag IDs", () => {
  Assert.assertEquals(isValidFlagId("flag\x00injection"), false);
  Assert.assertEquals(isValidFlagId("flag\u0000injection"), false);
});

Deno.test("Security: reject special shell characters in flag IDs", () => {
  let shellChars = [
    "flag;rm -rf /",
    "flag$(whoami)",
    "flag`id`",
    "flag|cat",
    "flag&sleep 10",
    "flag>output.txt"
  ];
  shellChars.forEach(id => {
    Assert.assertEquals(isValidFlagId(id), false);
  });
});

Deno.test("Security: accept valid flag IDs", () => {
  let validIds = [
    "privacy.tracking",
    "perf.cache",
    "feature_new",
    "flag-123",
    "x",
    "A1.b2_c3-d4"
  ];
  validIds.forEach(id => {
    Assert.assertEquals(isValidFlagId(id), true);
  });
});

Deno.test("Security: reject empty flag IDs", () => {
  Assert.assertEquals(isValidFlagId(""), false);
  Assert.assertEquals(isValidFlagId(" "), false);
});

Deno.test("Security: escape HTML in flag values", () => {
  let xssPayloads = [
    "<script>alert(\"xss\")</script>",
    "<img src=x onerror=\"alert(1)\">",
    "<svg onload=\"alert(1)\">",
    "\"><script>alert(1)</script>",
    "javascript:alert(1)"
  ];
  xssPayloads.forEach(payload => {
    let escaped = escapeHtml(payload);
    Assert.assertEquals(escaped.includes("<"), false);
    Assert.assertEquals(escaped.includes(">"), false);
    Assert.assertEquals(escaped.length > 0, true);
  });
});

Deno.test("Security: escapeHtml preserves content", () => {
  let escaped = escapeHtml("Hello & <World> \"Test\"");
  Assert.assertStringIncludes(escaped, "Hello");
  Assert.assertStringIncludes(escaped, "World");
  Assert.assertStringIncludes(escaped, "Test");
});

Deno.test("Security: getSafeValue escapes string flags", () => {
  let flag = mkFlag("test", true, "<script>alert(\"xss\")</script>", "default", undefined, undefined);
  let safe = getSafeValue(flag);
  Assert.assertEquals(safe.includes("<script>"), false);
  Assert.assertEquals(safe.includes("&lt;script&gt;"), true);
});

Deno.test("Security: getSafeValue returns default when disabled", () => {
  let flag = mkFlag("test", false, "<script>alert(\"xss\")</script>", "safe-default", undefined, undefined);
  let safe = getSafeValue(flag);
  Assert.assertStringIncludes(safe, "safe-default");
});

Deno.test("Security: non-string values safely stringified", () => {
  let cases = [
    [
      123,
      "number"
    ],
    [
      true,
      "boolean"
    ],
    [
      null,
      "null"
    ],
    [
      {
        key: "value"
      },
      "object"
    ],
    [
      [
        1,
        2,
        3
      ],
      "array"
    ]
  ];
  cases.forEach(param => {
    let flag = mkFlag("test", true, param[0], "default", undefined, undefined);
    let safe = getSafeValue(flag);
    Assert.assertEquals(typeof safe, "string");
    Assert.assertEquals(safe.length > 0, true);
  });
});

Deno.test("Security: readonly flags cannot be modified", () => {
  let db = singleton("system.immutable", mkFlag("system.immutable", true, "original", "default", true, undefined));
  let result = modifyFlag("system.immutable", "new-value", db);
  Assert.assertEquals(result.success, false);
  Assert.assertEquals(result.error, "Flag is readonly");
  let flag = db["system.immutable"];
  Assert.assertEquals(flag.value, "original");
});

Deno.test("Security: writable flags can be modified", () => {
  let db = singleton("feature.mutable", mkFlag("feature.mutable", true, "original", "default", false, undefined));
  let result = modifyFlag("feature.mutable", "new-value", db);
  Assert.assertEquals(result.success, true);
  let flag = db["feature.mutable"];
  Assert.assertEquals(flag.value, "new-value");
});

Deno.test("Security: reject modification of nonexistent flags", () => {
  let db = {};
  let result = modifyFlag("nonexistent.flag", "value", db);
  Assert.assertEquals(result.success, false);
  Assert.assertEquals(result.error, "Flag not found");
});

Deno.test("Security: reject modification with invalid flag ID", () => {
  let db = singleton("valid.flag", mkFlag("valid.flag", true, "original", "default", undefined, undefined));
  let result = modifyFlag("../../../etc/passwd", "malicious", db);
  Assert.assertEquals(result.success, false);
  Assert.assertEquals(result.error, "Invalid flag ID");
});

Deno.test("Security: reject malformed JSON from DevTools", () => {
  let malformed = [
    "{invalid json}",
    "{'single': 'quotes'}",
    "{incomplete:",
    "{\"key\": undefined}",
    "{\"key\": function() {}}"
  ];
  malformed.forEach(json => {
    Assert.assertEquals(validateJson(json), false);
  });
});

Deno.test("Security: accept valid JSON from DevTools", () => {
  let validJson = [
    "{}",
    "{\"key\":\"value\"}",
    "[1,2,3]",
    "{\"nested\":{\"deep\":\"value\"}}",
    "null",
    "true",
    "123",
    "\"string\""
  ];
  validJson.forEach(json => {
    Assert.assertEquals(validateJson(json), true);
  });
});

Deno.test("Security: safeParseJson returns fallback on invalid JSON", () => {
  let fallback = {
    default: "value"
  };
  let result1 = safeParseJson("{invalid}", fallback);
  Assert.assertEquals(result1, fallback);
  let result2 = safeParseJson("{\"valid\":\"json\"}", fallback);
  Assert.assertEquals(result2.valid, "json");
});

Deno.test("Security: DevTools cannot inject arbitrary code", () => {
  let injectedJson = JSON.stringify({
    key: "test",
    constructor: {
      prototype: {
        polluted: true
      }
    }
  });
  let result = safeParseJson(injectedJson, {});
  Assert.assertEquals(typeof result, "object");
  let clean = {};
  let polluted = (function(o){return Object.prototype.hasOwnProperty.call(o,"polluted")})(clean);
  Assert.assertEquals(polluted, false);
});

Deno.test("Security: combined threat - malicious ID + XSS + JSON injection", () => {
  let db = singleton("safe.flag", mkFlag("safe.flag", true, "normal", "default", undefined, undefined));
  let result1 = modifyFlag("../../../etc/passwd", "<script>alert(\"xss\")</script>", db);
  Assert.assertEquals(result1.success, false);
  let flag = db["safe.flag"];
  Assert.assertEquals(flag.value, "normal");
  let fallback = {
    safe: true
  };
  let result2 = safeParseJson("{corrupted}", fallback);
  Assert.assertEquals(result2.safe, true);
});

Deno.test("Security: escapeHtml handles edge cases", () => {
  let cases = [
    [
      "",
      ""
    ],
    [
      "normal text",
      "normal text"
    ],
    [
      "&",
      "&amp;"
    ],
    [
      "&&",
      "&amp;&amp;"
    ],
    [
      "<>",
      "&lt;&gt;"
    ],
    [
      "\"\"",
      "&quot;&quot;"
    ],
    [
      "''",
      "&#039;&#039;"
    ],
    [
      "&<>\"'",
      "&amp;&lt;&gt;&quot;&#039;"
    ]
  ];
  cases.forEach(param => {
    let result = escapeHtml(param[0]);
    Assert.assertEquals(result, param[1]);
  });
});

Deno.test("Security: all readonly flags remain protected", () => {
  let db = {};
  db["system.flag1"] = mkFlag("system.flag1", true, "v1", "d1", true, undefined);
  db["system.flag2"] = mkFlag("system.flag2", true, "v2", "d2", true, undefined);
  db["user.flag"] = mkFlag("user.flag", true, "v3", "d3", false, undefined);
  Assert.assertEquals(modifyFlag("system.flag1", "hacked", db).success, false);
  Assert.assertEquals(modifyFlag("system.flag2", "hacked", db).success, false);
  Assert.assertEquals(modifyFlag("user.flag", "allowed", db).success, true);
  Assert.assertEquals(db["system.flag1"].value, "v1");
  Assert.assertEquals(db["system.flag2"].value, "v2");
  Assert.assertEquals(db["user.flag"].value, "allowed");
});

let htmlEntityMap = d;

export {
  idRegex,
  isValidFlagId,
  htmlEntityMap,
  htmlEscapeRegex,
  escapeHtml,
  getSafeValue,
  validateJson,
  safeParseJson,
  isFlagReadonly,
  modifyFlag,
  mkFlag,
  singleton,
}
/*  Not a pure module */
