// SPDX-License-Identifier: MPL-2.0
// Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Assert from "std/assert";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let undefinedV = undefined;

function evaluateFlag(flagId, database, context) {
  let flag = database[flagId];
  if (flag === undefined) {
    return undefinedV;
  }
  let envs = flag.requiredEnvironments;
  let envOK = envs !== undefined && envs.length !== 0 ? envs.includes(context.currentEnvironment) : true;
  if (!envOK) {
    return flag.defaultValue;
  }
  if (!flag.enabled) {
    return flag.defaultValue;
  }
  let match = flag.overrides;
  let match$1 = context.userId;
  if (match === undefined) {
    return flag.value;
  }
  if (match$1 === undefined) {
    return flag.value;
  }
  let v = match[match$1];
  if (v !== undefined) {
    return Primitive_option.valFromOption(v);
  } else {
    return flag.value;
  }
}

function getAllFlags(database, context) {
  let result = {};
  Object.keys(database).forEach(key => {
    result[key] = evaluateFlag(key, database, context);
  });
  return result;
}

function getFlagsByCategory(database, category, context) {
  let result = {};
  let prefix = category + ".";
  Object.keys(database).forEach(key => {
    if (key.startsWith(prefix)) {
      result[key] = evaluateFlag(key, database, context);
      return;
    }
  });
  return result;
}

function mkFlag(key, enabled, value, defaultValue, reqEnvs, overrides, param) {
  return {
    key: key,
    enabled: enabled,
    value: value,
    defaultValue: defaultValue,
    environment: undefined,
    requiredEnvironments: reqEnvs,
    overrides: overrides
  };
}

function mkContext(env, userId, param) {
  return {
    currentEnvironment: env,
    userId: userId,
    userAttributes: undefined
  };
}

function singleton(key, flag) {
  let d = {};
  d[key] = flag;
  return d;
}

Deno.test("Flag evaluation: enabled boolean flag returns its value", () => {
  let db = singleton("privacy.tracking", {
    key: "privacy.tracking",
    enabled: true,
    value: true,
    defaultValue: false,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  });
  let context = {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  };
  let result = evaluateFlag("privacy.tracking", db, context);
  Assert.assertStrictEquals(result, true);
});

Deno.test("Flag evaluation: enabled string flag returns its value", () => {
  let db = singleton("feature.mode", {
    key: "feature.mode",
    enabled: true,
    value: "fast",
    defaultValue: "standard",
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  });
  let result = evaluateFlag("feature.mode", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(result, "fast");
});

Deno.test("Flag evaluation: enabled numeric flag returns its value", () => {
  let db = singleton("perf.timeout", {
    key: "perf.timeout",
    enabled: true,
    value: 5000,
    defaultValue: 3000,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  });
  let result = evaluateFlag("perf.timeout", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(result, 5000);
});

Deno.test("Flag evaluation: disabled flag returns default value", () => {
  let db = singleton("feature.new", {
    key: "feature.new",
    enabled: false,
    value: true,
    defaultValue: false,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  });
  let result = evaluateFlag("feature.new", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(result, false);
});

Deno.test("Flag evaluation: disabled flag ignores its value", () => {
  let db = singleton("feature.experimental", {
    key: "feature.experimental",
    enabled: false,
    value: "enabled-value",
    defaultValue: "disabled-value",
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  });
  let result = evaluateFlag("feature.experimental", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(result, "disabled-value");
});

Deno.test("Flag evaluation: disabled numeric flag returns default", () => {
  let db = singleton("perf.workers", {
    key: "perf.workers",
    enabled: false,
    value: 4,
    defaultValue: 1,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  });
  let result = evaluateFlag("perf.workers", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(result, 1);
});

Deno.test("Flag evaluation: missing flag returns undefined (no crash)", () => {
  let db = {};
  let result = evaluateFlag("nonexistent.flag", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(result, undefinedV);
});

Deno.test("Flag evaluation: missing flag does not throw", () => {
  let db = {};
  let context = {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  };
  try {
    let result = evaluateFlag("nonexistent.flag", db, context);
    Assert.assertEquals(result, undefinedV);
    return;
  } catch (exn) {
    return Stdlib_Exn.raiseError("Flag evaluation should not throw for missing flag");
  }
});

Deno.test("Flag evaluation: graceful handling of undefined in database", () => {
  let db = {};
  let context = {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  };
  for (let i = 0; i <= 99; ++i) {
    let result = evaluateFlag("flag." + i.toString(), db, context);
    Assert.assertStrictEquals(result, undefinedV);
  }
});

Deno.test("Flag evaluation: environment filter - prod only flag not in dev", () => {
  let db = singleton("feature.prod-only", mkFlag("feature.prod-only", true, true, false, ["production"], undefined, undefined));
  let prodResult = evaluateFlag("feature.prod-only", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(prodResult, true);
  let devResult = evaluateFlag("feature.prod-only", db, {
    currentEnvironment: "development",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(devResult, false);
});

Deno.test("Flag evaluation: environment filter allows multiple environments", () => {
  let db = singleton("feature.staging-prod", mkFlag("feature.staging-prod", true, true, false, [
    "production",
    "staging"
  ], undefined, undefined));
  let cases = [
    [
      "production",
      true
    ],
    [
      "staging",
      true
    ],
    [
      "development",
      false
    ],
    [
      "test",
      false
    ]
  ];
  cases.forEach(param => {
    let result = evaluateFlag("feature.staging-prod", db, {
      currentEnvironment: param[0],
      userId: undefined,
      userAttributes: undefined
    });
    Assert.assertStrictEquals(result, param[1]);
  });
});

Deno.test("Flag evaluation: no environment restriction means all environments", () => {
  let db = singleton("feature.all-envs", {
    key: "feature.all-envs",
    enabled: true,
    value: "available",
    defaultValue: "default",
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  });
  let envs = [
    "production",
    "staging",
    "development",
    "test"
  ];
  envs.forEach(env => {
    let result = evaluateFlag("feature.all-envs", db, {
      currentEnvironment: env,
      userId: undefined,
      userAttributes: undefined
    });
    Assert.assertStrictEquals(result, "available");
  });
});

Deno.test("Flag evaluation: override takes precedence over value", () => {
  let overrides = {};
  overrides["user-123"] = "user-specific-value";
  let db = singleton("feature.customized", mkFlag("feature.customized", true, "default-value", "fallback", undefined, overrides, undefined));
  let noUser = evaluateFlag("feature.customized", db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertStrictEquals(noUser, "default-value");
  let user123 = evaluateFlag("feature.customized", db, {
    currentEnvironment: "production",
    userId: "user-123",
    userAttributes: undefined
  });
  Assert.assertStrictEquals(user123, "user-specific-value");
  let user456 = evaluateFlag("feature.customized", db, {
    currentEnvironment: "production",
    userId: "user-456",
    userAttributes: undefined
  });
  Assert.assertStrictEquals(user456, "default-value");
});

Deno.test("Flag evaluation: multiple overrides for different users", () => {
  let overrides = {};
  overrides["user-a"] = true;
  overrides["user-b"] = true;
  overrides["user-c"] = false;
  let db = singleton("feature.user-specific", mkFlag("feature.user-specific", true, false, false, undefined, overrides, undefined));
  let users = [
    [
      "user-a",
      true
    ],
    [
      "user-b",
      true
    ],
    [
      "user-c",
      false
    ],
    [
      "user-d",
      false
    ]
  ];
  users.forEach(param => {
    let result = evaluateFlag("feature.user-specific", db, {
      currentEnvironment: "production",
      userId: param[0],
      userAttributes: undefined
    });
    Assert.assertStrictEquals(result, param[1]);
  });
});

Deno.test("Flag evaluation: get all flags in database", () => {
  let db = {};
  db["feature.one"] = {
    key: "feature.one",
    enabled: true,
    value: 1,
    defaultValue: 0,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  };
  db["feature.two"] = {
    key: "feature.two",
    enabled: false,
    value: 2,
    defaultValue: 20,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  };
  db["feature.three"] = {
    key: "feature.three",
    enabled: true,
    value: 3,
    defaultValue: 30,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  };
  let all = getAllFlags(db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertEquals(Object.keys(all).length, 3);
  Assert.assertStrictEquals(all["feature.one"], 1);
  Assert.assertStrictEquals(all["feature.two"], 20);
  Assert.assertStrictEquals(all["feature.three"], 3);
});

Deno.test("Flag evaluation: get flags by category", () => {
  let db = {};
  db["privacy.tracking"] = {
    key: "privacy.tracking",
    enabled: true,
    value: false,
    defaultValue: true,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  };
  db["privacy.cookies"] = {
    key: "privacy.cookies",
    enabled: false,
    value: true,
    defaultValue: false,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  };
  db["perf.caching"] = {
    key: "perf.caching",
    enabled: true,
    value: true,
    defaultValue: false,
    environment: undefined,
    requiredEnvironments: undefined,
    overrides: undefined
  };
  let privacyFlags = getFlagsByCategory(db, "privacy", {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertEquals(Object.keys(privacyFlags).length, 2);
  Assert.assertStrictEquals(privacyFlags["privacy.tracking"], Primitive_option.some(false));
  Assert.assertStrictEquals(privacyFlags["privacy.cookies"], Primitive_option.some(false));
});

Deno.test("Flag evaluation: override + environment filter interaction", () => {
  let overrides = {};
  overrides["user-vip"] = "vip-value";
  let db = singleton("feature.complex", mkFlag("feature.complex", true, "prod-value", "default", ["production"], overrides, undefined));
  let vipProd = evaluateFlag("feature.complex", db, {
    currentEnvironment: "production",
    userId: "user-vip",
    userAttributes: undefined
  });
  Assert.assertEquals(vipProd, "vip-value");
  let regProd = evaluateFlag("feature.complex", db, {
    currentEnvironment: "production",
    userId: "user-regular",
    userAttributes: undefined
  });
  Assert.assertEquals(regProd, "prod-value");
  let vipDev = evaluateFlag("feature.complex", db, {
    currentEnvironment: "development",
    userId: "user-vip",
    userAttributes: undefined
  });
  Assert.assertEquals(vipDev, "default");
});

Deno.test("Flag evaluation: disabled flag ignores overrides", () => {
  let overrides = {};
  overrides["user-123"] = "override-value";
  let db = singleton("feature.disabled-override", mkFlag("feature.disabled-override", false, "enabled-value", "default-value", undefined, overrides, undefined));
  let result = evaluateFlag("feature.disabled-override", db, {
    currentEnvironment: "production",
    userId: "user-123",
    userAttributes: undefined
  });
  Assert.assertStrictEquals(result, "default-value");
});

Deno.test("Flag evaluation: batch evaluation of 100 flags", () => {
  let db = {};
  for (let i = 0; i <= 99; ++i) {
    db["flag." + i.toString()] = mkFlag("flag." + i.toString(), i % 2 === 0, i, 0, undefined, undefined, undefined);
  }
  let all = getAllFlags(db, {
    currentEnvironment: "production",
    userId: undefined,
    userAttributes: undefined
  });
  Assert.assertEquals(Object.keys(all).length, 100);
  for (let i$1 = 0; i$1 <= 99; ++i$1) {
    let expected = i$1 % 2 === 0 ? i$1 : 0;
    Assert.assertStrictEquals(all["flag." + i$1.toString()], Primitive_option.some(expected));
  }
});

export {
  undefinedV,
  evaluateFlag,
  getAllFlags,
  getFlagsByCategory,
  mkFlag,
  mkContext,
  singleton,
}
/*  Not a pure module */
