// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Assert from "std/assert";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function validateFlagKey(key) {
  if (typeof key === "string" && !(key == null)) {
    return key.length > 0;
  } else {
    return false;
  }
}

function validateFlagValue(value, t) {
  switch (t) {
    case "boolean" :
      return typeof value === "boolean";
    case "string" :
      return typeof value === "string";
    case "integer" :
      if (typeof value === "number") {
        return Number.isInteger(value);
      } else {
        return false;
      }
    case "float" :
      return typeof value === "number";
  }
}

function validateFlag(flag) {
  let errors = [];
  if (!validateFlagKey(flag.key)) {
    errors.push("Flag key must be non-empty string");
  }
  if (flag.description.length === 0) {
    errors.push("Flag must have a description");
  }
  if (!validateFlagValue(flag.defaultValue, flag.type)) {
    let match = flag.type;
    let tmp;
    switch (match) {
      case "boolean" :
        tmp = "boolean";
        break;
      case "string" :
        tmp = "string";
        break;
      case "integer" :
        tmp = "integer";
        break;
      case "float" :
        tmp = "float";
        break;
    }
    let msg = "Default value does not match type " + tmp;
    errors.push(msg);
  }
  return {
    valid: errors.length === 0,
    errors: errors
  };
}

let emptyEffects_positive = [];

let emptyEffects_negative = [];

let emptyEffects_interesting = [];

let emptyEffects = {
  positive: emptyEffects_positive,
  negative: emptyEffects_negative,
  interesting: emptyEffects_interesting
};

Deno.test("Flag keys: non-empty string requirement", () => {
  Assert.assertEquals(validateFlagKey("privacy.tracking"), true);
  Assert.assertEquals(validateFlagKey("perf.optimization"), true);
  Assert.assertEquals(validateFlagKey("x"), true);
  Assert.assertEquals(validateFlagKey(""), false);
  Assert.assertEquals(validateFlagKey(null), false);
  Assert.assertEquals(validateFlagKey(undefined), false);
  Assert.assertEquals(validateFlagKey(123), false);
});

Deno.test("Flag keys: dot notation allowed", () => {
  Assert.assertEquals(validateFlagKey("privacy.tracking"), true);
  Assert.assertEquals(validateFlagKey("perf.cache.enabled"), true);
  Assert.assertEquals(validateFlagKey("feature_flag_1"), true);
});

Deno.test("Flag values: boolean type", () => {
  Assert.assertEquals("boolean" === "boolean", true);
  Assert.assertEquals("boolean" === "boolean", true);
  Assert.assertEquals("string" === "boolean", false);
  Assert.assertEquals("number" === "boolean", false);
  let value = null;
  Assert.assertEquals(typeof value === "boolean", false);
});

Deno.test("Flag values: string type", () => {
  Assert.assertEquals("string" === "string", true);
  Assert.assertEquals("string" === "string", true);
  Assert.assertEquals("string" === "string", true);
  Assert.assertEquals("number" === "string", false);
  Assert.assertEquals("boolean" === "string", false);
});

Deno.test("Flag values: integer type", () => {
  Assert.assertEquals(validateFlagValue(0, "integer"), true);
  Assert.assertEquals(validateFlagValue(42, "integer"), true);
  Assert.assertEquals(validateFlagValue(-100, "integer"), true);
  Assert.assertEquals(validateFlagValue(3.14, "integer"), false);
  Assert.assertEquals(validateFlagValue("42", "integer"), false);
});

Deno.test("Flag values: float type", () => {
  Assert.assertEquals("number" === "number", true);
  Assert.assertEquals("number" === "number", true);
  Assert.assertEquals("number" === "number", true);
  Assert.assertEquals("number" === "number", true);
  Assert.assertEquals("string" === "number", false);
  Assert.assertEquals("boolean" === "number", false);
});

Deno.test("Flag config: required fields validation", () => {
  let validFlag_permissions = [];
  let validFlag = {
    key: "test.flag",
    type: "boolean",
    category: "experimental",
    safetyLevel: "safe",
    defaultValue: false,
    description: "Test flag",
    effects: emptyEffects,
    permissions: validFlag_permissions,
    geckoMinVersion: undefined,
    geckoMaxVersion: undefined,
    documentation: undefined,
    bugNumber: undefined
  };
  let result = validateFlag(validFlag);
  Assert.assertEquals(result.valid, true);
  Assert.assertEquals(result.errors.length, 0);
});

Deno.test("Flag config: all required fields must be present", () => {
  let noKey_permissions = [];
  let noKey = {
    key: "",
    type: "boolean",
    category: "experimental",
    safetyLevel: "safe",
    defaultValue: false,
    description: "Test",
    effects: emptyEffects,
    permissions: noKey_permissions,
    geckoMinVersion: undefined,
    geckoMaxVersion: undefined,
    documentation: undefined,
    bugNumber: undefined
  };
  Assert.assertEquals(validateFlag(noKey).valid, false);
  let noDesc_permissions = [];
  let noDesc = {
    key: "test",
    type: "boolean",
    category: "experimental",
    safetyLevel: "safe",
    defaultValue: false,
    description: "",
    effects: emptyEffects,
    permissions: noDesc_permissions,
    geckoMinVersion: undefined,
    geckoMaxVersion: undefined,
    documentation: undefined,
    bugNumber: undefined
  };
  Assert.assertEquals(validateFlag(noDesc).valid, false);
});

Deno.test("Flag config: default value type mismatch detection", () => {
  let mismatch_permissions = [];
  let mismatch = {
    key: "test.flag",
    type: "boolean",
    category: "experimental",
    safetyLevel: "safe",
    defaultValue: "true",
    description: "Test flag",
    effects: emptyEffects,
    permissions: mismatch_permissions,
    geckoMinVersion: undefined,
    geckoMaxVersion: undefined,
    documentation: undefined,
    bugNumber: undefined
  };
  let result = validateFlag(mismatch);
  Assert.assertEquals(result.valid, false);
  Assert.assertEquals(result.errors.some(e => e.includes("Default value does not match")), true);
});

Deno.test("Safety levels: all variants recognized", () => {
  let levels = [
    "safe",
    "experimental",
    "dangerous"
  ];
  levels.forEach(level => {
    let flag_permissions = [];
    let flag = {
      key: "test",
      type: "boolean",
      category: "experimental",
      safetyLevel: level,
      defaultValue: false,
      description: "Test",
      effects: emptyEffects,
      permissions: flag_permissions,
      geckoMinVersion: undefined,
      geckoMaxVersion: undefined,
      documentation: undefined,
      bugNumber: undefined
    };
    Assert.assertEquals(validateFlag(flag).valid, true);
  });
});

Deno.test("Safety levels: invalid level detection", () => {
  let flag_safetyLevel = "unknown";
  let flag_permissions = [];
  let flag = {
    key: "test",
    type: "boolean",
    category: "experimental",
    safetyLevel: flag_safetyLevel,
    defaultValue: false,
    description: "Test",
    effects: emptyEffects,
    permissions: flag_permissions,
    geckoMinVersion: undefined,
    geckoMaxVersion: undefined,
    documentation: undefined,
    bugNumber: undefined
  };
  validateFlag(flag);
  Assert.assertEquals(typeof flag_safetyLevel, "string");
});

Deno.test("Categories: all variants recognized", () => {
  let categories = [
    "privacy",
    "performance",
    "experimental",
    "developer",
    "ui",
    "network"
  ];
  categories.forEach(category => {
    let flag_permissions = [];
    let flag = {
      key: "test",
      type: "boolean",
      category: category,
      safetyLevel: "safe",
      defaultValue: false,
      description: "Test",
      effects: emptyEffects,
      permissions: flag_permissions,
      geckoMinVersion: undefined,
      geckoMaxVersion: undefined,
      documentation: undefined,
      bugNumber: undefined
    };
    Assert.assertEquals(validateFlag(flag).valid, true);
  });
});

Deno.test("Flag state: creation with defaults", () => {
  Assert.assertEquals("privacy.tracking", "privacy.tracking");
  Assert.assertEquals(false, false);
  Assert.assertEquals(false, false);
});

Deno.test("Flag state: tracks modifications", () => {
  let state_lastModified = Date.now();
  let state_modifiedBy = "user";
  Assert.assertEquals(true, true);
  Assert.assertExists(state_lastModified);
  Assert.assertEquals("user", "user");
});

Deno.test("Flag state: valid modification sources", () => {
  let sources = [
    "user",
    "extension",
    "system"
  ];
  sources.forEach(source => {
    let state_modifiedBy = source;
    Assert.assertEquals(state_modifiedBy, source);
  });
});

Deno.test("Flag change: complete change record", () => {
  let change_timestamp = Date.now();
  let change_effects = {
    positive: ["less tracking"],
    negative: ["slower page load"],
    interesting: ["ads may be more relevant"]
  };
  Assert.assertEquals("privacy.tracking", "privacy.tracking");
  Assert.assertEquals(false, false);
  Assert.assertEquals(true, true);
  Assert.assertExists(change_timestamp);
  Assert.assertEquals("user", "user");
  Assert.assertExists(change_effects);
});

Deno.test("Flag database: empty database structure", () => {
  let db_lastUpdated = new Date().toISOString();
  let db_categories = {};
  let db_flags = [];
  Assert.assertEquals("0.1.0", "0.1.0");
  Assert.assertEquals(db_flags.length, 0);
  Assert.assertEquals(Object.keys(db_categories).length, 0);
});

Deno.test("Flag database: with categories and flags", () => {
  let categories = {};
  categories["privacy"] = {
    name: "Privacy Features",
    description: "User privacy controls"
  };
  categories["performance"] = {
    name: "Performance",
    description: "Performance optimizations"
  };
  let db_lastUpdated = new Date().toISOString();
  let db_flags = [{
      key: "privacy.tracking",
      type: "boolean",
      category: "privacy",
      safetyLevel: "safe",
      defaultValue: false,
      description: "Disable tracking",
      effects: emptyEffects,
      permissions: ["privacy"],
      geckoMinVersion: undefined,
      geckoMaxVersion: undefined,
      documentation: undefined,
      bugNumber: undefined
    }];
  Assert.assertEquals("1.0.0", "1.0.0");
  Assert.assertEquals(db_flags.length, 1);
  Assert.assertEquals(Object.keys(categories).length, 2);
  Assert.assertEquals(Stdlib_Option.map(db_flags[0], f => f.key), "privacy.tracking");
});

Deno.test("Environments: all variants valid", () => {
  let environments = [
    "production",
    "staging",
    "development",
    "test"
  ];
  let valid = [
    "production",
    "staging",
    "development",
    "test"
  ];
  environments.forEach(env => {
    Assert.assertEquals(valid.includes(env), true);
  });
});

Deno.test("Permissions: all browser permissions valid", () => {
  let perms = [
    "browserSettings",
    "privacy",
    "tabs",
    "notifications",
    "downloads"
  ];
  let validStrings = [
    "browserSettings",
    "privacy",
    "tabs",
    "notifications",
    "downloads"
  ];
  perms.forEach(perm => {
    Assert.assertEquals(validStrings.includes(perm), true);
  });
});

Deno.test("Permissions: flag can have multiple permissions", () => {
  let flag_permissions = [
    "browserSettings",
    "privacy",
    "notifications"
  ];
  Assert.assertEquals(flag_permissions.length, 3);
  Assert.assertEquals(flag_permissions[0], "browserSettings");
});

Deno.test("Type composition: flag effects structure", () => {
  let effects_positive = [
    "faster loading",
    "less memory"
  ];
  let effects_negative = ["fewer features"];
  let effects_interesting = ["affects ad targeting"];
  Assert.assertEquals(effects_positive.length, 2);
  Assert.assertEquals(effects_negative.length, 1);
  Assert.assertEquals(effects_interesting.length, 1);
});

Deno.test("Type composition: category metadata", () => {
  Assert.assertEquals("string", "string");
  Assert.assertEquals("string", "string");
  Assert.assertEquals("Privacy Controls".length > 0, true);
});

export {
  validateFlagKey,
  validateFlagValue,
  validateFlag,
  emptyEffects,
}
/*  Not a pure module */
